### ISSUE TITLE
edits to be made in quadrat.locations.csv

### ISSUE THREAD

**Issue by emchristensen** [LCRoysterproject/Data#30]
- [x] Dist_frm values missing from Nov 6-8 2017 (Raw data corrected 3/15/18)

- [x] March 2018 data to be added

- [x] There are still a few missing Dist_frm values in the raw file LCR_oyster_grid_2013_2017.xls: lines 256, 258, 258, 261, 262 (10/27/2014)...Steve:  Only lines 256-258 fixable (no data for others on datasheet)

- [x] non-numeric Dist_frm values in LCR_oyster_grid_2013_2017.xls: lines 308-311 (Does L/r correspond to the Left/Right Direction column from the 2010 data?)...Steve: Yes, non-numerics removed

- [x] missing information for 10/27/2010 and 12/8/2010 (lines 5965-5978 in Grid_data_Nov_2012_bp). I need help interpreting this....Steve:  No datasheets found, but reference to test sites in GIS files.  I deleted these values since there was no data for these entries

- [ ] missing Dist_along Dist_from info from 7/8/2010 and 5/23/2010...Steve: No datasheets found, unresolved

- [x] also in the 2010 data: does a "." in a cell mean NA? (I see them particularly in the Recorder and Direction columns)...Steve:  safe assumption

- [x] on 7/11/2011, Direction column, "cont'd". I assume this means the value should mirror the value in the cell above it: I need to handle this in the code...Steve:  not a continuation of previous cell, corrected all using datasheets

- [ ] missing Dist_from value 10/16/2012, CRN1, (line 16637 in Grid_data_Nov_2012_bp)...Steve: no datasheets found, unresolved

- [x] all Quad_type = "SURFACE", Quad_area = 0.0625, Quad_depth = NA (except 12/20/2017, 1/17/2018, 1/30/2018) -- I made this change, except I do not see any quadrat data for 12/20/2017 or 1/17/2018 in the repo

**Comment by billpine** [comment]
This looks like it is close to be finished. Thanks for working on this.

**Comment by emchristensen** [comment]
I think we've resolved this issue to the best of our ability (there are still a few missing values, but if we don't have the original data sheets they're unlikely to be filled). I'll close this issue, but it can always be reopened if necessary.
